// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillForge.Core.Data;

#nullable disable

namespace SkillForge.Core.Migrations
{
    [DbContext(typeof(SkillForgeDbContext))]
    partial class SkillForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillForge.Core.Models.GameRound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GameSubtype")
                        .HasColumnType("integer");

                    b.Property<int?>("Player1Correct")
                        .HasColumnType("integer");

                    b.Property<string>("Player1Data")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Player1TimeMs")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2Correct")
                        .HasColumnType("integer");

                    b.Property<string>("Player2Data")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Player2TimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("SkillForge.Core.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisconnectionInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<string>("Player1SkillDelta")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Player2IsAi")
                        .HasColumnType("boolean");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<string>("Player2SkillDelta")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("Status");

                    b.HasIndex("Player1Id", "Player2Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SkillForge.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillForge.Core.Models.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentile")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("RankCountry")
                        .HasColumnType("integer");

                    b.Property<int?>("RankGlobal")
                        .HasColumnType("integer");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SkillType", "Percentile");

                    b.HasIndex("SkillType", "XP");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("SkillForge.Core.Models.GameRound", b =>
                {
                    b.HasOne("SkillForge.Core.Models.GameSession", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SkillForge.Core.Models.GameSession", b =>
                {
                    b.HasOne("SkillForge.Core.Models.User", "Player1")
                        .WithMany("GameSessionsAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillForge.Core.Models.User", "Player2")
                        .WithMany("GameSessionsAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("SkillForge.Core.Models.UserSkill", b =>
                {
                    b.HasOne("SkillForge.Core.Models.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillForge.Core.Models.GameSession", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("SkillForge.Core.Models.User", b =>
                {
                    b.Navigation("GameSessionsAsPlayer1");

                    b.Navigation("GameSessionsAsPlayer2");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
